### ISSUE TITLE
Code Formatting Check fails on develop: trailing whitespace in metacall.c

### ISSUE THREAD

**Issue by bhuvan-somisetty** [metacall/core#900]
## 🐛 Bug Report

The Code Formatting Check has been failing on `develop` since 0960e3b6 (#893). Line 511 of `source/metacall/source/metacall.c` is a blank line made of two tabs, and clang-format flags it:

```
source/metacall/source/metacall.c:510:55: error: code should be clang-formatted [-Wclang-format-violations]
Failed on file: source/metacall/source/metacall.c
```

### Expected Behavior

The Code Formatting Check passes on `develop`.

### Current Behavior

It fails on every `develop` commit since 0960e3b6:

- eeccbe44: success (https://github.com/metacall/core/actions/runs/35641332671)
- 0960e3b6: failure (https://github.com/metacall/core/actions/runs/35643731276)
- 7025c425: failure (https://github.com/metacall/core/actions/runs/35779326950)
- f3be8700: failure (https://github.com/metacall/core/actions/runs/35891230365)

Because the check runs on the whole tree, it also fails on every open PR, even ones that don't touch this file (I saw it on #897).

### Possible Solution

Delete the two tabs on line 511 so it becomes an empty line. It's the only line with trailing whitespace in the file.

### Steps to Reproduce

1. `git checkout develop` (f3be8700)
2. `sed -n 511p source/metacall/source/metacall.c | od -c` prints `\t \t \n`
3. Run clang-format 12, the version CI pins: `clang-format-12 --dry-run -Werror source/metacall/source/metacall.c` reports the violation at 510:55. Other versions also flag unrelated lines.

### Context (Environment)

Found while checking the CI results on #897. With this check red on every PR, it's harder to tell real formatting problems apart.

### Detailed Description

It's a one-line whitespace fix and doesn't change any behaviour.

### Possible Implementation

```diff
 		length = strnlen(paths[iterator], LOADER_PATH_SIZE);
-		
+
 		if (length >= LOADER_PATH_SIZE)
```
